name: bullseye
description: A new flavour of regex in Dart.
version: 0.1.1
homepage: https://www.github.com/Qwerp-Derp/bullseye
author: Hanyuan Li <completelyderp@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
